
import { Question, ForcedChoiceQuestion, SJTQuestion } from './types';

export const ENGAGEMENT_QUESTIONS: Question[] = [
  // Standard (First 10) - Baseline Pool (8 will be picked randomly)
  { id: 'e1', textEn: 'Do you feel your work has a purpose?', textHi: 'क्या आपको लगता है कि आपके काम का कोई उद्देश्य है?', dimension: 'Purpose', purpose: 'Engagement', framework: 'Gallup Q12', adaptiveTag: 'Standard' },
  { id: 'e2', textEn: 'Do you clearly understand your role?', textHi: 'क्या आप अपनी भूमिका को स्पष्ट रूप से समझते हैं?', dimension: 'Clarity', purpose: 'Engagement', framework: 'Gallup Q12', adaptiveTag: 'Standard' },
  { id: 'e3', textEn: 'Does your work energize you?', textHi: 'क्या आपका काम आपको ऊर्जा देता है?', dimension: 'Vigor', purpose: 'Engagement', framework: 'UWES-9', adaptiveTag: 'Standard' },
  { id: 'e4', textEn: 'Do you have the tools needed to work?', textHi: 'क्या आपके पास काम करने के लिए आवश्यक उपकरण हैं?', dimension: 'Resources', purpose: 'Engagement', framework: 'Gallup Q12', adaptiveTag: 'Standard' },
  { id: 'e5', textEn: 'Do team members help one another?', textHi: 'क्या टीम के सदस्य एक-दूसरे की मदद करते हैं?', dimension: 'Teamwork', purpose: 'Engagement', framework: 'Gallup Q12', adaptiveTag: 'Standard' },
  { id: 'e6', textEn: 'Have you received recognition for good work recently?', textHi: 'क्या आपको हाल ही में अच्छे काम के लिए सराहना मिली है?', dimension: 'Recognition', purpose: 'Engagement', framework: 'Gallup Q12', adaptiveTag: 'Standard' },
  { id: 'e7', textEn: 'Does the factory environment allow you to work comfortably?', textHi: 'क्या फैक्ट्री का वातावरण आपको आराम से काम करने की अनुमति देता है?', dimension: 'Environment', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'Standard' },
  { id: 'e8', textEn: 'Do you feel you have a good balance between work and home?', textHi: 'क्या आपको लगता है कि आपके काम और घर के बीच अच्छा संतुलन है?', dimension: 'Balance', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'Standard' },
  { id: 'e9', textEn: 'Is your opinion valued at work?', textHi: 'क्या काम पर आपकी राय को महत्व दिया जाता है?', dimension: 'Impact', purpose: 'Engagement', framework: 'Gallup Q12', adaptiveTag: 'Standard' },
  { id: 'e10', textEn: 'Does your supervisor care about you as a person?', textHi: 'क्या आपका सुपरवाइजर एक व्यक्ति के रूप में आपकी परवाह करता है?', dimension: 'Support', purpose: 'Engagement', framework: 'Gallup Q12', adaptiveTag: 'Standard' },
  
  // High Engagement Path (Growth & Leadership - 7 will be picked randomly)
  { id: 'e_hi_1', textEn: 'Do you look for ways to improve factory processes?', textHi: 'क्या आप फैक्ट्री की प्रक्रियाओं को बेहतर बनाने के तरीके खोजते हैं?', dimension: 'Innovation', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },
  { id: 'e_hi_2', textEn: 'Do you feel proud when your team hits a target?', textHi: 'क्या आपको गर्व महसूस होता है जब आपकी टीम लक्ष्य हासिल करती है?', dimension: 'Ownership', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },
  { id: 'e_hi_3', textEn: 'Would you recommend this factory to a friend?', textHi: 'क्या आप अपने किसी मित्र को इस फैक्ट्री में काम करने की सलाह देंगे?', dimension: 'Loyalty', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },
  { id: 'e_hi_4', textEn: 'Do you feel your suggestions are valued by management?', textHi: 'क्या आपको लगता है कि आपके सुझावों को प्रबंधन द्वारा महत्व दिया जाता है?', dimension: 'Impact', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },
  { id: 'e_hi_5', textEn: 'Are you interested in learning more advanced skills?', textHi: 'क्या आप अधिक उन्नत कौशल सीखने में रुचि रखते हैं?', dimension: 'Growth', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },
  { id: 'e_hi_6', textEn: 'Do you see yourself growing into a leadership role here?', textHi: 'क्या आप खुद को यहाँ नेतृत्व की भूमिका में बढ़ते हुए देखते हैं?', dimension: 'Vision', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },
  { id: 'e_hi_7', textEn: 'Do you actively mentor new joiners in your line?', textHi: 'क्या आप अपनी लाइन में नए जुड़ने वालों को सक्रिय रूप से मेंटर करते हैं?', dimension: 'Mentorship', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },
  { id: 'e_hi_8', textEn: 'Do you find ways to save waste in your daily tasks?', textHi: 'क्या आप अपने दैनिक कार्यों में कचरे को बचाने के तरीके ढूंढते हैं?', dimension: 'Sustainability', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'HighEngagement' },

  // Low Engagement Path (Well-being & Safety - 7 will be picked randomly)
  { id: 'e_lo_1', textEn: 'Do you feel physically safe at work?', textHi: 'क्या आप काम पर शारीरिक रूप से सुरक्षित महसूस करते हैं?', dimension: 'Safety', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' },
  { id: 'e_lo_2', textEn: 'Is your supervisor fair in their treatment?', textHi: 'क्या आपका सुपरवाइजर अपने व्यवहार में निष्पक्ष है?', dimension: 'Fairness', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' },
  { id: 'e_lo_3', textEn: 'Is the workload manageable for you?', textHi: 'क्या आपके लिए कार्यभार प्रबंधनीय है?', dimension: 'Well-being', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' },
  { id: 'e_lo_4', textEn: 'Do you receive regular feedback on your performance?', textHi: 'क्या आपको अपने प्रदर्शन पर नियमित फीडबैक मिलता है?', dimension: 'Communication', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' },
  { id: 'e_lo_5', textEn: 'Do you feel respected by your colleagues?', textHi: 'क्या आप अपने सहयोगियों द्वारा सम्मानित महसूस करते हैं?', dimension: 'Respect', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' },
  { id: 'e_lo_6', textEn: 'Are the rest areas and facilities adequate?', textHi: 'क्या विश्राम क्षेत्र और सुविधाएं पर्याप्त हैं?', dimension: 'Facilities', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' },
  { id: 'e_lo_7', textEn: 'Do you feel comfortable reporting errors to your senior?', textHi: 'क्या आप अपने वरिष्ठ को गलतियों की रिपोर्ट करने में सहज महसूस करते हैं?', dimension: 'Openness', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' },
  { id: 'e_lo_8', textEn: 'Is the commute to the factory stressful for you?', textHi: 'क्या फैक्ट्री तक का सफर आपके लिए तनावपूर्ण है?', dimension: 'Personal', purpose: 'Engagement', framework: 'Custom', adaptiveTag: 'LowEngagement' }
];

export const BEHAVIORAL_QUESTIONS: ForcedChoiceQuestion[] = [
  { id: 'b1', scenarioEn: 'When facing pressure, I usually:', scenarioHi: 'दबाव का सामना करते हुए, मैं आमतौर पर:', options: { A: { textEn: 'Prioritize speed.', textHi: 'गति को प्राथमिकता देता हूँ।', trait: 'Executor' }, B: { textEn: 'Prioritize accuracy.', textHi: 'सटीकता को प्राथमिकता देता हूँ।', trait: 'Guardian' } } },
  { id: 'b2', scenarioEn: 'When a teammate struggles, I:', scenarioHi: 'जब कोई साथी संघर्ष करता है, तो मैं:', options: { A: { textEn: 'Step in to help directly.', textHi: 'सीधे मदद के लिए कदम उठाता हूँ।', trait: 'Harmonizer' }, B: { textEn: 'Report to the supervisor.', textHi: 'सुपरवाइजर को रिपोर्ट करता हूँ।', trait: 'Informer' } } },
  { id: 'b3', scenarioEn: 'I prefer work that is:', scenarioHi: 'मैं ऐसा काम पसंद करता हूँ जो:', options: { A: { textEn: 'Steady and routine.', textHi: 'स्थिर और नियमित हो।', trait: 'Guardian' }, B: { textEn: 'Changing and active.', textHi: 'बदलने वाला और सक्रिय हो।', trait: 'Executor' } } },
  { id: 'b4', scenarioEn: 'Mistakes are best handled by:', scenarioHi: 'गलतियों को सबसे अच्छी तरह संभाला जाता है:', options: { A: { textEn: 'Fixing them quietly.', textHi: 'चुपचाप ठीक करके।', trait: 'Guardian' }, B: { textEn: 'Sharing for learning.', textHi: 'सीखने के लिए साझा करके।', trait: 'Informer' } } },
  { id: 'b5', scenarioEn: 'I am motivated by:', scenarioHi: 'मैं इससे प्रेरित होता हूँ:', options: { A: { textEn: 'Personal achievement.', textHi: 'व्यक्तिगत उपलब्धि।', trait: 'Executor' }, B: { textEn: 'Team success.', textHi: 'टीम की सफलता।', trait: 'Harmonizer' } } },
  { id: 'b6', scenarioEn: 'In a group meeting, I usually:', scenarioHi: 'एक समूह बैठक में, मैं आमतौर पर:', options: { A: { textEn: 'Listen more than I speak.', textHi: 'बोलने से ज्यादा सुनता हूं।', trait: 'Guardian' }, B: { textEn: 'Share my ideas quickly.', textHi: 'अपने विचार जल्दी साझा करता हूं।', trait: 'Informer' } } },
  { id: 'b7', scenarioEn: 'When learning a new tool, I:', scenarioHi: 'जब मैं कोई नया टूल सीखता हूं, तो मैं:', options: { A: { textEn: 'Try it out immediately.', textHi: 'इसे तुरंत आज़माता हूं।', trait: 'Executor' }, B: { textEn: 'Read the manual carefully.', textHi: 'मैनुअल को ध्यान से पढ़ता हूं।', trait: 'Guardian' } } },
  { id: 'b8', scenarioEn: 'Conflict at work makes me:', scenarioHi: 'काम पर विवाद मुझे:', options: { A: { textEn: 'Try to calm everyone down.', textHi: 'सभी को शांत करने की कोशिश करने के लिए प्रेरित करता है।', trait: 'Harmonizer' }, B: { textEn: 'Focus strictly on the facts.', textHi: 'सख्ती से तथ्यों पर ध्यान केंद्रित करने के लिए प्रेरित करता है।', trait: 'Informer' } } },
  { id: 'b9', scenarioEn: 'I value most:', scenarioHi: 'मैं सबसे अधिक महत्व देता हूं:', options: { A: { textEn: 'Reliability and trust.', textHi: 'विश्वसनीयता और भरोसा।', trait: 'Guardian' }, B: { textEn: 'Energy and action.', textHi: 'ऊर्जा और कार्य।', trait: 'Executor' } } },
  { id: 'b10', scenarioEn: 'When tasks are boring, I:', scenarioHi: 'जब कार्य उबाऊ होते हैं, तो मैं:', options: { A: { textEn: 'Find a way to make it fun.', textHi: 'इसे मज़ेदार बनाने का तरीका ढूंढता हूँ।', trait: 'Executor' }, B: { textEn: 'Focus on finishing it right.', textHi: 'इसे सही ढंग से पूरा करने पर ध्यान देता हूँ।', trait: 'Guardian' } } },
  { id: 'b11', scenarioEn: 'I feel most useful when:', scenarioHi: 'मैं सबसे उपयोगी महसूस करता हूं जब:', options: { A: { textEn: 'I help a teammate.', textHi: 'मैं किसी साथी की मदद करता हूं।', trait: 'Harmonizer' }, B: { textEn: 'I finish my quota early.', textHi: 'मैं अपना कोटा जल्दी पूरा कर लेता हूं।', trait: 'Executor' } } },
  { id: 'b12', scenarioEn: 'I prefer feedback that is:', scenarioHi: 'मैं ऐसा फीडबैक पसंद करता हूं जो:', options: { A: { textEn: 'Gentle and encouraging.', textHi: 'विनम्र और उत्साहजनक हो।', trait: 'Harmonizer' }, B: { textEn: 'Direct and honest.', textHi: 'सीधा और ईमानदार हो।', trait: 'Informer' } } },
  { id: 'b13', scenarioEn: 'If a rule is slightly broken:', scenarioHi: 'यदि कोई नियम थोड़ा टूटता है:', options: { A: { textEn: 'I fix it if it matters.', textHi: 'अगर यह महत्वपूर्ण है तो मैं इसे ठीक करता हूँ।', trait: 'Guardian' }, B: { textEn: 'I inform the supervisor.', textHi: 'मैं सुपरवाइजर को सूचित करता हूं।', trait: 'Informer' } } },
  { id: 'b14', scenarioEn: 'Starting the day, I like to:', scenarioHi: 'दिन की शुरुआत में, मैं पसंद करता हूं:', options: { A: { textEn: 'Jump straight into work.', textHi: 'सीधे काम में लग जाना।', trait: 'Executor' }, B: { textEn: 'Plan my sequence first.', textHi: 'पहले अपना क्रम बनाना।', trait: 'Guardian' } } },
  { id: 'b15', scenarioEn: 'In a crisis, I tend to:', scenarioHi: 'संकट में, मेरी प्रवृत्ति होती है:', options: { A: { textEn: 'Stay calm and observe.', textHi: 'शांत रहना और निरीक्षण करना।', trait: 'Guardian' }, B: { textEn: 'Take charge and act.', textHi: 'जिम्मा लेना और कार्य करना।', trait: 'Executor' } } }
];

export const SJT_QUESTIONS: SJTQuestion[] = [
  // Basic
  { id: 's1', complexity: 'Basic', scenarioEn: 'A colleague is using old tools, which might affect quality.', scenarioHi: 'एक सहकर्मी पुराने उपकरणों का उपयोग कर रहा है, जो गुणवत्ता को प्रभावित कर सकता है।', options: { A: { textEn: 'Inform supervisor.', textHi: 'सुपरवाइजर को सूचित करें।', alignment: 'High Initiative' }, B: { textEn: 'Lend your tools.', textHi: 'अपने उपकरण उधार दें।', alignment: 'Balanced Adaptability' }, C: { textEn: 'Wait and see.', textHi: 'प्रतीक्षा करें और देखें।', alignment: 'Risk-Averse' }, D: { textEn: 'Discuss later.', textHi: 'बाद में चर्चा करें।', alignment: 'Strategic' } } },
  { id: 's2', complexity: 'Basic', scenarioEn: 'The manager forgets a sudden schedule change alert.', scenarioHi: 'मैनेजर अचानक शेड्यूल परिवर्तन अलर्ट देना भूल गया।', options: { A: { textEn: 'Alert team individually.', textHi: 'टीम को व्यक्तिगत रूप से सचेत करें।', alignment: 'High Initiative' }, B: { textEn: 'Feedback to manager.', textHi: 'मैनेजर को फीडबैक दें।', alignment: 'Balanced Adaptability' }, C: { textEn: 'Report to HR.', textHi: 'एचआर को रिपोर्ट करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Suggest group chat.', textHi: 'ग्रुप चैट का सुझाव दें।', alignment: 'Strategic' } } },
  { id: 's3', complexity: 'Basic', scenarioEn: 'You see someone taking extra raw materials home.', scenarioHi: 'आप किसी को अतिरिक्त कच्चा माल घर ले जाते हुए देखते हैं।', options: { A: { textEn: 'Inform HR.', textHi: 'एचआर को सूचित करें।', alignment: 'High Initiative' }, B: { textEn: 'Talk to them privately.', textHi: 'उनसे निजी तौर पर बात करें।', alignment: 'Strategic' }, C: { textEn: 'Ignore it.', textHi: 'नज़रअंदाज़ करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Mention to senior.', textHi: 'सीनियर को बताएं।', alignment: 'Balanced Adaptability' } } },
  { id: 's4', complexity: 'Basic', scenarioEn: 'A safety barrier is loose on a machine.', scenarioHi: 'मशीन पर एक सुरक्षा घेरा ढीला है।', options: { A: { textEn: 'Stop and fix it.', textHi: 'रुकें और इसे ठीक करें।', alignment: 'High Initiative' }, B: { textEn: 'Mark with warning tape.', textHi: 'चेतावनी टेप से चिह्नित करें।', alignment: 'Strategic' }, C: { textEn: 'Tell the next shift.', textHi: 'अगली शिफ्ट को बताएं।', alignment: 'Risk-Averse' }, D: { textEn: 'Report to maintenance.', textHi: 'रखरखाव विभाग को रिपोर्ट करें।', alignment: 'Balanced Adaptability' } } },
  { id: 's5', complexity: 'Basic', scenarioEn: 'The team target is too high this month.', scenarioHi: 'इस महीने टीम का लक्ष्य बहुत ऊंचा है।', options: { A: { textEn: 'Organize extra hours.', textHi: 'अतिरिक्त घंटों का आयोजन करें।', alignment: 'High Initiative' }, B: { textEn: 'Ask for target review.', textHi: 'लक्ष्य समीक्षा के लिए कहें।', alignment: 'Strategic' }, C: { textEn: 'Work at normal speed.', textHi: 'सामान्य गति से काम करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Request more staff.', textHi: 'अधिक स्टाफ की मांग करें।', alignment: 'Balanced Adaptability' } } },
  { id: 's6', complexity: 'Basic', scenarioEn: 'A new worker is making many errors.', scenarioHi: 'एक नया कार्यकर्ता बहुत सारी गलतियां कर रहा है।', options: { A: { textEn: 'Mentor them personally.', textHi: 'उन्हें व्यक्तिगत रूप से मेंटर करें।', alignment: 'Strategic' }, B: { textEn: 'Report for retraining.', textHi: 'पुनः प्रशिक्षण के लिए रिपोर्ट करें।', alignment: 'High Initiative' }, C: { textEn: 'Let them learn slowly.', textHi: 'उन्हें धीरे-धीरे सीखने दें।', alignment: 'Risk-Averse' }, D: { textEn: 'Give them easier tasks.', textHi: 'उन्हें आसान काम दें।', alignment: 'Balanced Adaptability' } } },
  { id: 's7', complexity: 'Basic', scenarioEn: 'Raw material is of poor quality today.', scenarioHi: 'आज कच्चे माल की गुणवत्ता खराब है।', options: { A: { textEn: 'Reject the entire batch.', textHi: 'पूरे बैच को अस्वीकार करें।', alignment: 'High Initiative' }, B: { textEn: 'Consult QC manager.', textHi: 'क्यूसी मैनेजर से सलाह लें।', alignment: 'Strategic' }, C: { textEn: 'Use it carefully.', textHi: 'इसे सावधानी से प्रयोग करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Adjust machine settings.', textHi: 'मशीन सेटिंग्स समायोजित करें।', alignment: 'Balanced Adaptability' } } },
  { id: 's8', complexity: 'Basic', scenarioEn: 'There is a water leak in the canteen.', scenarioHi: 'कैंटीन में पानी का रिसाव हो रहा है।', options: { A: { textEn: 'Close the valve now.', textHi: 'अभी वाल्व बंद करें।', alignment: 'High Initiative' }, B: { textEn: 'Inform the admin head.', textHi: 'एडमिन हेड को सूचित करें।', alignment: 'Balanced Adaptability' }, C: { textEn: 'Avoid the wet area.', textHi: 'गीले क्षेत्र से बचें।', alignment: 'Risk-Averse' }, D: { textEn: 'Suggest better drainage.', textHi: 'बेहतर जल निकासी का सुझाव दें।', alignment: 'Strategic' } } },
  { id: 's9', complexity: 'Basic', scenarioEn: 'A colleague is late for the shift handover.', scenarioHi: 'एक सहकर्मी शिफ्ट हैंडओवर के लिए देर से आया है।', options: { A: { textEn: 'Start work alone.', textHi: 'अकेले काम शुरू करें।', alignment: 'High Initiative' }, B: { textEn: 'Wait for them.', textHi: 'उनका इंतज़ार करें।', alignment: 'Risk-Averse' }, C: { textEn: 'Call them immediately.', textHi: 'उन्हें तुरंत फोन करें।', alignment: 'Balanced Adaptability' }, D: { textEn: 'Brief them quickly later.', textHi: 'बाद में उन्हें जल्दी से जानकारी दें।', alignment: 'Strategic' } } },
  { id: 's10', complexity: 'Basic', scenarioEn: 'A minor spill of non-hazardous oil on the floor.', scenarioHi: 'फर्श पर गैर-खतरनाक तेल का मामूली रिसाव।', options: { A: { textEn: 'Clean it up immediately.', textHi: 'इसे तुरंत साफ करें।', alignment: 'High Initiative' }, B: { textEn: 'Put a caution sign.', textHi: 'सावधानी का संकेत लगाएं।', alignment: 'Balanced Adaptability' }, C: { textEn: 'Wait for cleaners.', textHi: 'सफाईकर्मियों का इंतज़ार करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Tell everyone passing.', textHi: 'वहां से गुजरने वाले सभी को बताएं।', alignment: 'Strategic' } } },
  { id: 's11', complexity: 'Basic', scenarioEn: 'You notice a tool is vibrating unusually.', scenarioHi: 'आप देखते हैं कि एक उपकरण असामान्य रूप से कंपन कर रहा है।', options: { A: { textEn: 'Switch it off now.', textHi: 'इसे अभी बंद कर दें।', alignment: 'High Initiative' }, B: { textEn: 'Check for loose bolts.', textHi: 'ढीले बोल्टों की जांच करें।', alignment: 'Strategic' }, C: { textEn: 'Ignore if it works.', textHi: 'यदि यह काम करता है तो नज़रअंदाज़ करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Report to supervisor.', textHi: 'सुपरवाइजर को रिपोर्ट करें।', alignment: 'Balanced Adaptability' } } },
  { id: 's12', complexity: 'Basic', scenarioEn: 'An emergency alarm sounds during lunch.', scenarioHi: 'लंच के दौरान आपातकालीन अलार्म बजता है।', options: { A: { textEn: 'Exit immediately.', textHi: 'तुरंत बाहर निकलें।', alignment: 'Risk-Averse' }, B: { textEn: 'Guide others to exit.', textHi: ' दूसरों को बाहर निकलने के लिए मार्गदर्शन करें।', alignment: 'High Initiative' }, C: { textEn: 'Wait for instructions.', textHi: 'निर्देशों का इंतज़ार करें।', alignment: 'Balanced Adaptability' }, D: { textEn: 'Check if it is real.', textHi: 'जांचें कि क्या यह असली है।', alignment: 'Strategic' } } },
  { id: 's13', complexity: 'Basic', scenarioEn: 'A customer visits the factory floor unexpectedly.', scenarioHi: 'एक ग्राहक अचानक फैक्ट्री फ्लोर पर आता है।', options: { A: { textEn: 'Keep working normally.', textHi: 'सामान्य रूप से काम जारी रखें।', alignment: 'Risk-Averse' }, B: { textEn: 'Greet and offer help.', textHi: 'अभिवादन करें और मदद की पेशकश करें।', alignment: 'Strategic' }, C: { textEn: 'Alert the supervisor.', textHi: 'सुपरवाइजर को सचेत करें।', alignment: 'Balanced Adaptability' }, D: { textEn: 'Ensure area is extra clean.', textHi: 'सुनिश्चित करें कि क्षेत्र अतिरिक्त साफ है।', alignment: 'High Initiative' } } },
  { id: 's14', complexity: 'Basic', scenarioEn: 'You find an unlabeled container in the raw material area.', scenarioHi: 'आपको कच्चे माल के क्षेत्र में एक बिना लेबल वाला कंटेनर मिलता है।', options: { A: { textEn: 'Move it to waste.', textHi: 'इसे कचरे में डाल दें।', alignment: 'Risk-Averse' }, B: { textEn: 'Identify content carefully.', textHi: 'सामग्री की सावधानीपूर्वक पहचान करें।', alignment: 'Strategic' }, C: { textEn: 'Report to shift lead.', textHi: 'शिफ्ट लीड को रिपोर्ट करें।', alignment: 'Balanced Adaptability' }, D: { textEn: 'Tag it as "Unknown".', textHi: 'इसे "अज्ञात" के रूप में टैग करें।', alignment: 'High Initiative' } } },
  { id: 's15', complexity: 'Basic', scenarioEn: 'A teammate is ignoring a small quality defect.', scenarioHi: 'एक साथी छोटी गुणवत्ता दोष को नज़रअंदाज़ कर रहा है।', options: { A: { textEn: 'Point it out to them.', textHi: 'उन्हें इसकी ओर इशारा करें।', alignment: 'High Initiative' }, B: { textEn: 'Fix it yourself quietly.', textHi: 'इसे खुद चुपचाप ठीक कर दें।', alignment: 'Balanced Adaptability' }, C: { textEn: 'Report it to QC.', textHi: 'इसे क्यूसी को रिपोर्ट करें।', alignment: 'Strategic' }, D: { textEn: 'Ignore it as well.', textHi: 'आप भी इसे नज़रअंदाज़ करें।', alignment: 'Risk-Averse' } } },

  // Advanced
  { id: 's_adv_1', complexity: 'Advanced', scenarioEn: 'A major flaw is found in the master process.', scenarioHi: 'मास्टर प्रक्रिया में एक बड़ी खामी पाई गई है।', options: { A: { textEn: 'Implement fix now.', textHi: 'अभी सुधार लागू करें।', alignment: 'High Initiative' }, B: { textEn: 'Present formal proposal.', textHi: 'औपचारिक प्रस्ताव प्रस्तुत करें।', alignment: 'Strategic' }, C: { textEn: 'Ask for rule change.', textHi: 'नियम परिवर्तन के लिए कहें।', alignment: 'Balanced Adaptability' }, D: { textEn: 'Follow old way strictly.', textHi: 'पुरानी पद्धति का सख्ती से पालन करें।', alignment: 'Risk-Averse' } } },
  { id: 's_adv_2', complexity: 'Advanced', scenarioEn: 'Budget cuts force a choice: Safety or Speed?', scenarioHi: 'बजट में कटौती मजबूर करती है: सुरक्षा या गति?', options: { A: { textEn: 'Safety is non-negotiable.', textHi: 'सुरक्षा अपरिहार्य है।', alignment: 'Risk-Averse' }, B: { textEn: 'Middle ground solution.', textHi: 'बीच का रास्ता समाधान।', alignment: 'Balanced Adaptability' }, C: { textEn: 'Ask team for consensus.', textHi: 'टीम से आम सहमति मांगें।', alignment: 'Strategic' }, D: { textEn: 'Request data-led budget.', textHi: 'डेटा-आधारित बजट का अनुरोध करें।', alignment: 'High Initiative' } } },
  { id: 's_adv_3', complexity: 'Advanced', scenarioEn: 'A senior manager asks to ignore a minor quality check.', scenarioHi: 'एक वरिष्ठ प्रबंधक मामूली गुणवत्ता जांच को नज़रअंदाज़ करने के लिए कहता है।', options: { A: { textEn: 'Refuse and report.', textHi: 'मना करें और रिपोर्ट करें।', alignment: 'High Initiative' }, B: { textEn: 'Confirm with QC head.', textHi: 'क्यूसी हेड से पुष्टि करें।', alignment: 'Strategic' }, C: { textEn: 'Do it once as exception.', textHi: 'अपवाद के रूप में एक बार करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Log it in shift report.', textHi: 'इसे शिफ्ट रिपोर्ट में दर्ज करें।', alignment: 'Balanced Adaptability' } } },
  { id: 's_adv_4', complexity: 'Advanced', scenarioEn: 'Two critical machines break at the same time.', scenarioHi: 'एक ही समय में दो महत्वपूर्ण मशीनें खराब हो जाती हैं।', options: { A: { textEn: 'Redirect all labor now.', textHi: 'अभी सभी श्रम को मोड़ें।', alignment: 'High Initiative' }, B: { textEn: 'Prioritize based on ROI.', textHi: 'ROI के आधार पर प्राथमिकता दें।', alignment: 'Strategic' }, C: { textEn: 'Wait for technicians.', textHi: 'तकनीशियनों की प्रतीक्षा करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Suggest manual backup.', textHi: 'मैनुअल बैकअप का सुझाव दें।', alignment: 'Balanced Adaptability' } } },
  { id: 's_adv_5', complexity: 'Advanced', scenarioEn: 'A competitor is hiring away your best workers.', scenarioHi: 'एक प्रतिद्वंद्वी आपके सबसे अच्छे कार्यकर्ताओं को काम पर रख रहा है।', options: { A: { textEn: 'Pitch for better bonuses.', textHi: 'बेहतर बोनस के लिए पिच करें।', alignment: 'High Initiative' }, B: { textEn: 'Review retention strategy.', textHi: 'प्रतिधारण रणनीति की समीक्षा करें।', alignment: 'Strategic' }, C: { textEn: 'Hire new staff quickly.', textHi: 'जल्दी से नए स्टाफ की भर्ती करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Interview exiting staff.', textHi: 'छोड़ने वाले स्टाफ का इंटरव्यू लें।', alignment: 'Balanced Adaptability' } } },
  { id: 's_adv_6', complexity: 'Advanced', scenarioEn: 'The supply chain is delayed by 48 hours.', scenarioHi: 'आपूर्ति श्रृंखला में 48 घंटे की देरी है।', options: { A: { textEn: 'Reorder production flow.', textHi: 'उत्पादन प्रवाह को पुनर्व्यवस्थित करें।', alignment: 'Strategic' }, B: { textEn: 'Negotiate with suppliers.', textHi: 'आपूर्तिकर्ताओं के साथ बातचीत करें।', alignment: 'High Initiative' }, C: { textEn: 'Notify all customers.', textHi: 'सभी ग्राहकों को सूचित करें।', alignment: 'Balanced Adaptability' }, D: { textEn: 'Reduce shift hours.', textHi: 'शिफ्ट के घंटे कम करें।', alignment: 'Risk-Averse' } } },
  { id: 's_adv_7', complexity: 'Advanced', scenarioEn: 'A conflict arises between two veteran supervisors.', scenarioHi: 'दो अनुभवी पर्यवेक्षकों के बीच संघर्ष उत्पन्न होता है।', options: { A: { textEn: 'Mediate a session.', textHi: 'एक सत्र की मध्यस्थता करें।', alignment: 'Strategic' }, B: { textEn: 'Escalate to Plant Head.', textHi: 'प्लांट हेड को भेजें।', alignment: 'Balanced Adaptability' }, C: { textEn: 'Enforce neutral protocol.', textHi: 'तटस्थ प्रोटोकॉल लागू करें।', alignment: 'High Initiative' }, D: { textEn: 'Let them resolve it.', textHi: 'उन्हें इसे सुलझाने दें।', alignment: 'Risk-Averse' } } },
  { id: 's_adv_8', complexity: 'Advanced', scenarioEn: 'A digital tool upgrade is causing confusion.', scenarioHi: 'एक डिजिटल टूल अपग्रेड भ्रम पैदा कर रहा है।', options: { A: { textEn: 'Run a mini-workshop.', textHi: 'एक मिनी-वर्कशॉप चलाएं।', alignment: 'High Initiative' }, B: { textEn: 'Revert to paper logs.', textHi: 'कागज लॉग पर वापस लौटें।', alignment: 'Risk-Averse' }, C: { textEn: 'Gather user feedback.', textHi: 'उपयोगकर्ता फीडबैक एकत्र करें।', alignment: 'Balanced Adaptability' }, D: { textEn: 'Draft a FAQ guide.', textHi: 'एक FAQ गाइड तैयार करें।', alignment: 'Strategic' } } },
  { id: 's_adv_9', complexity: 'Advanced', scenarioEn: 'Employee turnover is affecting machine uptime.', scenarioHi: 'कर्मचारी टर्नओवर मशीन अपटाइम को प्रभावित कर रहा है।', options: { A: { textEn: 'Incentivize attendance.', textHi: 'उपस्थिति को प्रोत्साहित करें।', alignment: 'High Initiative' }, B: { textEn: 'Cross-train all teams.', textHi: 'सभी टीमों को क्रॉस-ट्रेन करें।', alignment: 'Strategic' }, C: { textEn: 'Hire temp agencies.', textHi: 'अस्थायी एजेंसियों को काम पर रखें।', alignment: 'Risk-Averse' }, D: { textEn: 'Audit workload stress.', textHi: 'कार्यभार तनाव का ऑडिट करें।', alignment: 'Balanced Adaptability' } } },
  { id: 's_adv_10', complexity: 'Advanced', scenarioEn: 'Energy costs spiked by 20% this quarter.', scenarioHi: 'इस तिमाही में ऊर्जा लागत में 20% की वृद्धि हुई है।', options: { A: { textEn: 'Audit power leakages.', textHi: 'पावर लीकेज का ऑडिट करें।', alignment: 'High Initiative' }, B: { textEn: 'Shift heavy tasks off-peak.', textHi: 'भारी कार्यों को ऑफ-पीक पर शिफ्ट करें।', alignment: 'Strategic' }, C: { textEn: 'Reduce lighting usage.', textHi: 'प्रकाश के उपयोग को कम करें।', alignment: 'Risk-Averse' }, D: { textEn: 'Propose solar investment.', textHi: 'सौर निवेश का प्रस्ताव दें।', alignment: 'Balanced Adaptability' } } }
];
